### ISSUE TITLE
ban/banip: index out of range

### ISSUE THREAD

**Issue by 01dog** [leighmacdonald/gbans#19]
these are missing checks (or need higher minArgs) if someone only uses 1 argument (like !ban asdf)
```
panic: runtime error: index out of range [1] with length 1

goroutine 153 [running]:
github.com/leighmacdonald/gbans/service.onBanIP(0xc0002aed80, 0xc000006048, 0xc0004bc2d0, 0x1, 0x1, 0x0, 0xc0004bc2d0)
        Y:/tf2server/gbans/service/bot_handlers.go:153 +0x6a6
github.com/leighmacdonald/gbans/service.onMessageCreate(0xc0002aed80, 0xc000006048)
        Y:/tf2server/gbans/service/bot.go:164 +0x431
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x1917730, 0xc0002aed80, 0x17d9b80, 0xc000006048)
        C:/Users/dog/go/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/eventhandlers.go:497 +0x52
created by github.com/bwmarrin/discordgo.(*Session).handle
        C:/Users/dog/go/pkg/mod/github.com/bwmarrin/discordgo@v0.22.0/event.go:171 +0x118
```

**Comment by leighmacdonald** [comment]
Thanks, this should no longer be an issue once slash commands are added, which is already underway.
